# Generated by Django 3.2 on 2023-01-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='locked_files',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
