# Generated by Django 4.1.1 on 2022-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_commit_date_created_alter_commit_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='unique_id',
            field=models.CharField(default=12, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.TextField(max_length=1500),
        ),
    ]
