// Authentication
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// Messaging
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// User action types
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const MODIFY_USER_SUCCESS = "MODIFY_USER_SUCCESS";
export const MODIFY_USER_FAIL = "MODIFY_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

// User data action types
export const GET_USER_REPOS_SUCCESS = "GET_USER_REPOS_SUCCESS";
export const GET_USER_REPOS_FAIL = "GET_USER_REPOS_FAIL";
export const GET_USER_BRANCHES_SUCCESS = "GET_USER_BRANCHES_SUCCESS";
export const GET_USER_BRANCHES_FAIL = "GET_USER_BRANCHES_FAIL";
export const GET_USER_COMMITS_SUCCESS = "GET_USER_COMMITS_SUCCESS";
export const GET_USER_COMMITS_FAIL = "GET_USER_COMMITS_FAIL";

// Repository action types
export const GET_ALL_REPOS_SUCCESS = "GET_ALL_REPOS_SUCCESS";
export const GET_ALL_REPOS_FAIL = "GET_ALL_REPOS_FAIL";
export const GET_REPO_SUCCESS = "GET_REPO_SUCCESS";
export const GET_REPO_FAIL = "GET_REPO_FAIL";
export const CREATE_REPO_SUCCESS = "CREATE_REPO_SUCCESS";
export const CREATE_REPO_FAIL = "CREATE_REPO_FAIL";
export const MODIFY_REPO_SUCCESS = "MODIFY_REPO_SUCCESS";
export const MODIFY_REPO_FAIL = "MODIFY_REPO_FAIL";
export const DELETE_REPO_SUCCESS = "DELETE_REPO_SUCCESS";
export const DELETE_REPO_FAIL = "DELETE_REPO_FAIL";

// Branch action types
export const GET_ALL_BRANCHES_SUCCESS = "GET_ALL_BRANCHES_SUCCESS";
export const GET_ALL_BRANCHES_FAIL = "GET_ALL_BRANCHES_FAIL";
export const GET_BRANCH_SUCCESS = "GET_BRANCH_SUCCESS";
export const GET_BRANCH_FAIL = "GET_BRANCH_FAIL";
export const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS";
export const CREATE_BRANCH_FAIL = "CREATE_BRANCH_FAIL";
export const MODIFY_BRANCH_SUCCESS = "MODIFY_BRANCH_SUCCESS";
export const MODIFY_BRANCH_FAIL = "MODIFY_BRANCH_FAIL";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_FAIL = "DELETE_BRANCH_FAIL";

// Commit action types
export const GET_ALL_COMMITS_SUCCESS = "GET_ALL_COMMITS_SUCCESS";
export const GET_ALL_COMMITS_FAIL = "GET_ALL_COMMITS_FAIL";
export const GET_COMMIT_SUCCESS = "GET_COMMIT_SUCCESS";
export const GET_COMMIT_FAIL = "GET_COMMIT_FAIL";
export const MODIFY_COMMIT_SUCCESS = "MODIFY_COMMIT_SUCCESS";
export const MODIFY_COMMIT_FAIL = "MODIFY_COMMIT_FAIL";
export const DELETE_COMMIT_SUCCESS = "DELETE_COMMIT_SUCCESS";
export const DELETE_COMMIT_FAIL = "DELETE_COMMIT_FAIL";
export const GET_COMMIT_FILE_TREE_SUCCESS = "GET_COMMIT_FILE_TREE_SUCCESS"
export const GET_COMMIT_FILE_TREE_FAIL = "GET_COMMIT_FILE_TREE_FAIL"
